from __future__ import annotations

import platform
import sys
from pathlib import Path
from typing import Any

from .io import read_json, write_json
from .records import now

RUNTIME_ENVIRONMENT_MANIFEST_FILE = "runtime_environment_manifest.json"
RUNTIME_ENVIRONMENT_SUMMARY_FILE = "runtime_environment_summary.json"

BOUNDARY_NOTES = [
    "evidence != truth",
    "operational validation != scientific validity",
    "approval record != agent permission",
    "dry-run != physical execution",
    "NeuML handoff != claim promotion",
    "simulated adapter != hardware adapter",
]


def build_runtime_environment_manifest(*, created_at: str | None = None) -> dict[str, Any]:
    """Build a small reproducibility manifest for the local simulated run.

    This captures the Python/runtime context used to create the simulated evidence
    packet. It intentionally does not install packages, call the network, access
    hardware, approve execution, validate scientific truth, or promote claims.
    """

    return {
        "record_type": "runtime_environment_manifest",
        "created_at": created_at or now(),
        "environment_scope": "operational_simulation_only",
        "implementation_language": "Python",
        "python_version": sys.version.split()[0],
        "python_implementation": platform.python_implementation(),
        "platform_system": platform.system() or "unknown",
        "platform_release": platform.release() or "unknown",
        "package_name": "trace_lab",
        "entry_points": [
            "python -m trace_lab.cli run-demo",
            "python -m trace_lab.cli validate",
            "python -m trace_lab.cli state-summary",
            "python -m trace_lab.cli review-summary",
            "python -m trace_lab.cli adapter-summary",
            "python -m trace_lab.cli environment-summary",
            "python -m trace_lab.cli build-neuml-handoff",
        ],
        "runtime_notes": [
            "Generated by the TraceLab v0.1 simulated demo path.",
            "No hardware APIs, device drivers, network calls, or package installation are required.",
        ],
        "package_installation_performed": False,
        "network_calls_performed": False,
        "hardware_access_performed": False,
        "physical_execution_completed": False,
        "scientific_truth_validated": False,
        "authority_flags": {
            "agent_approved": False,
            "physical_execution_completed": False,
            "scientific_truth_validated": False,
            "state_promoted": False,
            "claims_promoted": False,
            "package_installation_performed": False,
            "network_calls_performed": False,
            "hardware_access_performed": False,
        },
        "boundary_notes": BOUNDARY_NOTES,
        "authority_note": "Runtime environment evidence is reproducibility context only; it does not validate scientific truth, execute hardware, or promote claims.",
    }


def write_runtime_environment_manifest(run_dir: str | Path, *, force: bool = False) -> Path:
    """Write runtime_environment_manifest.json, refusing silent overwrite by default."""

    run_dir = Path(run_dir)
    path = run_dir / RUNTIME_ENVIRONMENT_MANIFEST_FILE
    if path.exists() and not force:
        raise FileExistsError(
            "TraceLab refuses to overwrite runtime_environment_manifest.json without force=True. "
            "This prevents silent replacement of runtime evidence."
        )
    write_json(path, build_runtime_environment_manifest())
    return path


def validate_runtime_environment_manifest(manifest: dict[str, Any]) -> dict[str, list[str]]:
    """Validate runtime-environment evidence and its v0.1 authority boundary."""

    environment_errors: list[str] = []
    unsafe: list[str] = []

    if not isinstance(manifest, dict):
        return {
            "environment_errors": ["runtime_environment_manifest.json is not a JSON object."],
            "unsafe": [],
        }

    if manifest.get("record_type") != "runtime_environment_manifest":
        environment_errors.append("runtime_environment_manifest.json record_type must be runtime_environment_manifest.")
    if manifest.get("environment_scope") != "operational_simulation_only":
        environment_errors.append("runtime_environment_manifest.json environment_scope must be operational_simulation_only.")
    if manifest.get("implementation_language") != "Python":
        environment_errors.append("runtime_environment_manifest.json implementation_language must be Python.")
    if not manifest.get("python_version"):
        environment_errors.append("runtime_environment_manifest.json must include python_version.")
    if not manifest.get("python_implementation"):
        environment_errors.append("runtime_environment_manifest.json must include python_implementation.")
    if not manifest.get("platform_system"):
        environment_errors.append("runtime_environment_manifest.json must include platform_system.")
    if manifest.get("package_name") != "trace_lab":
        environment_errors.append("runtime_environment_manifest.json package_name must be trace_lab.")

    entry_points = manifest.get("entry_points", [])
    if not isinstance(entry_points, list):
        environment_errors.append("runtime_environment_manifest.json entry_points must be a list.")
    elif "python -m trace_lab.cli run-demo" not in entry_points:
        environment_errors.append("runtime_environment_manifest.json entry_points must include the run-demo CLI entry point.")

    for field in [
        "package_installation_performed",
        "network_calls_performed",
        "hardware_access_performed",
        "physical_execution_completed",
        "scientific_truth_validated",
    ]:
        if manifest.get(field):
            unsafe.append(f"runtime_environment_manifest.json cannot set {field}=true in v0.1 simulation.")

    flags = manifest.get("authority_flags", {})
    if not isinstance(flags, dict):
        environment_errors.append("runtime_environment_manifest.json authority_flags must be an object.")
        flags = {}

    for flag in [
        "agent_approved",
        "physical_execution_completed",
        "scientific_truth_validated",
        "state_promoted",
        "claims_promoted",
        "package_installation_performed",
        "network_calls_performed",
        "hardware_access_performed",
    ]:
        if flags.get(flag):
            unsafe.append(f"runtime_environment_manifest.json authority_flags cannot set {flag}=true in v0.1 simulation.")

    boundary_notes = manifest.get("boundary_notes", [])
    for note in BOUNDARY_NOTES:
        if note not in boundary_notes:
            environment_errors.append(f"runtime_environment_manifest.json boundary_notes missing: {note}")

    return {"environment_errors": environment_errors, "unsafe": unsafe}


def build_runtime_environment_summary(run_dir: str | Path) -> dict[str, Any]:
    """Build an operator-facing runtime summary without mutating run evidence."""

    run_dir = Path(run_dir)
    manifest = read_json(run_dir / RUNTIME_ENVIRONMENT_MANIFEST_FILE)
    validation = validate_runtime_environment_manifest(manifest)

    return {
        "record_type": "runtime_environment_summary",
        "created_at": now(),
        "environment_summary_status": (
            "runtime_context_recorded"
            if not validation["environment_errors"] and not validation["unsafe"]
            else "runtime_context_has_errors"
        ),
        "environment_scope": manifest.get("environment_scope"),
        "implementation_language": manifest.get("implementation_language"),
        "python_version": manifest.get("python_version"),
        "python_implementation": manifest.get("python_implementation"),
        "platform_system": manifest.get("platform_system"),
        "package_name": manifest.get("package_name"),
        "package_installation_performed": manifest.get("package_installation_performed"),
        "network_calls_performed": manifest.get("network_calls_performed"),
        "hardware_access_performed": manifest.get("hardware_access_performed"),
        "environment_errors": validation["environment_errors"],
        "unsafe": validation["unsafe"],
        "boundary_notes": BOUNDARY_NOTES,
        "authority_note": "Runtime environment summary is an operator-facing trace view only; it does not install packages, call hardware, validate scientific truth, or promote claims.",
    }


def write_runtime_environment_summary(run_dir: str | Path, *, force: bool = False) -> Path:
    """Write runtime_environment_summary.json, refusing silent overwrite by default."""

    run_dir = Path(run_dir)
    path = run_dir / RUNTIME_ENVIRONMENT_SUMMARY_FILE
    if path.exists() and not force:
        raise FileExistsError(
            "TraceLab refuses to overwrite runtime_environment_summary.json without force=True. "
            "This prevents silent replacement of runtime summary evidence."
        )
    write_json(path, build_runtime_environment_summary(run_dir))
    return path
